New Header update w/ clickable userid
SanDiegoWebDevBootCamp/sangstagram-web pull request #4
Opened 2019-11-29 05:22 UTC by byum1996

2019-11-30 06:17 UTC, justinyum98 commented on src/posts/PublishedDate.js
> +            <div className="left-align-board">
`className="left-align-board"` by itself won't left align the board. You will need to use CSS, or Material-UI's [styling feature](https://material-ui.com/styles/basics/). Give this a read.

2019-11-30 06:18 UTC, justinyum98 commented on src/posts/UserId.js
> +            </button>
Nice 👍

2019-11-30 06:19 UTC, justinyum98 requested changes
Suggested some changes 👍

2019-11-30 06:19 UTC, justinyum98 commented on src/posts/UserId.js
> +
Delete these extra lines, no purpose in them.

2019-11-30 14:50 UTC, sangyum commented on src/posts/PublishedDate.js
> +                <p>{this.props.publishedDate.toString()}</p>
`publishedDate` is a Javascript Date object. Javascript Date object has many function that prints out the date in different format. `toString()` is probably not the function we want to use. Consider other functions, after reviewing https://www.w3schools.com/jsref/jsref_todatestring.asp and other functions.

2019-11-30 14:50 UTC, sangyum commented on src/posts/UserId.js
> +            </button>
➕

2019-11-30 14:50 UTC, sangyum commented on src/stories/3-Header.stories.js
> +export const headerRender = () => <Header publishedDate={publishedDate} userId={userId}/>
line feed at the end of file

2019-12-02 04:33 UTC, justinyum98 approved these changes
👍

2019-12-02 04:33 UTC, merged